"""initial schema

Revision ID: 0001
Revises:
Create Date: 2026-09-24 20:35:33.662609
"""

from __future__ import annotations

import sqlalchemy as sa

from alembic import op

revision = "0001"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "audit_log",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("ts", sa.DateTime(timezone=True), nullable=False),
        sa.Column("actor", sa.String(length=64), nullable=False),
        sa.Column("action", sa.String(length=64), nullable=False),
        sa.Column("entity_type", sa.String(length=32), nullable=False),
        sa.Column("entity_id", sa.String(length=64), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("prev_hash", sa.String(length=64), nullable=False),
        sa.Column("hash", sa.String(length=64), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("hash"),
    )
    with op.batch_alter_table("audit_log", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_audit_log_action"), ["action"], unique=False)
        batch_op.create_index(batch_op.f("ix_audit_log_entity_id"), ["entity_id"], unique=False)

    op.create_table(
        "llm_calls",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("task", sa.String(length=48), nullable=False),
        sa.Column("mode", sa.String(length=16), nullable=False),
        sa.Column("model", sa.String(length=64), nullable=False),
        sa.Column("latency_ms", sa.Float(), nullable=False),
        sa.Column("prompt_tokens", sa.Integer(), nullable=True),
        sa.Column("completion_tokens", sa.Integer(), nullable=True),
        sa.Column("error_kind", sa.String(length=24), nullable=True),
        sa.Column("application_id", sa.String(length=20), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("llm_calls", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_llm_calls_application_id"), ["application_id"], unique=False
        )

    op.create_table(
        "models",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("version", sa.String(length=32), nullable=False),
        sa.Column("role", sa.String(length=16), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("metrics", sa.JSON(), nullable=False),
        sa.Column("card", sa.JSON(), nullable=False),
        sa.Column("artifact_path", sa.Text(), nullable=False),
        sa.Column("approvals", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "outbox",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("event", sa.String(length=64), nullable=False),
        sa.Column("aggregate_id", sa.String(length=64), nullable=False),
        sa.Column("channel", sa.String(length=16), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("idempotency_key", sa.String(length=128), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("delivered_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("idempotency_key", name="uq_outbox_idempotency"),
    )
    with op.batch_alter_table("outbox", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_outbox_aggregate_id"), ["aggregate_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_outbox_event"), ["event"], unique=False)
        batch_op.create_index(batch_op.f("ix_outbox_status"), ["status"], unique=False)

    op.create_table(
        "rule_sets",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("backtest", sa.JSON(), nullable=False),
        sa.Column("approvals", sa.JSON(), nullable=False),
        sa.Column("activated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("username", sa.String(length=64), nullable=False),
        sa.Column("full_name", sa.String(length=120), nullable=False),
        sa.Column("role", sa.String(length=32), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_users_role"), ["role"], unique=False)
        batch_op.create_index(batch_op.f("ix_users_username"), ["username"], unique=True)

    op.create_table(
        "applicants",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("owner_user_id", sa.String(length=32), nullable=True),
        sa.Column("tckn_enc", sa.Text(), nullable=True),
        sa.Column("tckn_bidx", sa.String(length=64), nullable=True),
        sa.Column("name_enc", sa.Text(), nullable=True),
        sa.Column("phone_enc", sa.Text(), nullable=True),
        sa.Column("phone_bidx", sa.String(length=64), nullable=True),
        sa.Column("email_enc", sa.Text(), nullable=True),
        sa.Column("address_enc", sa.Text(), nullable=True),
        sa.Column("address_bidx", sa.String(length=64), nullable=True),
        sa.Column("iban_enc", sa.Text(), nullable=True),
        sa.Column("iban_bidx", sa.String(length=64), nullable=True),
        sa.Column("birth_date", sa.Date(), nullable=True),
        sa.Column("gender", sa.String(length=8), nullable=True),
        sa.Column("province", sa.String(length=40), nullable=True),
        sa.Column("anonymized_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["owner_user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("applicants", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_applicants_address_bidx"), ["address_bidx"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_applicants_iban_bidx"), ["iban_bidx"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_applicants_owner_user_id"), ["owner_user_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_applicants_phone_bidx"), ["phone_bidx"], unique=False)
        batch_op.create_index(batch_op.f("ix_applicants_tckn_bidx"), ["tckn_bidx"], unique=False)

    op.create_table(
        "applications",
        sa.Column("id", sa.String(length=20), nullable=False),
        sa.Column("applicant_id", sa.String(length=32), nullable=False),
        sa.Column("owner_user_id", sa.String(length=32), nullable=True),
        sa.Column("state", sa.String(length=32), nullable=False),
        sa.Column("product", sa.String(length=32), nullable=False),
        sa.Column("requested_amount", sa.Float(), nullable=False),
        sa.Column("requested_term_months", sa.Integer(), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("declared_income", sa.Float(), nullable=False),
        sa.Column("employment_type", sa.String(length=16), nullable=False),
        sa.Column("employer_name", sa.String(length=120), nullable=True),
        sa.Column("device_id", sa.String(length=64), nullable=True),
        sa.Column("persona", sa.String(length=32), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("submitted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("decided_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("sla_due_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("assigned_to", sa.String(length=64), nullable=True),
        sa.Column("priority", sa.Float(), nullable=False),
        sa.Column("kyc", sa.JSON(), nullable=False),
        sa.Column("letters", sa.JSON(), nullable=False),
        sa.Column("reports", sa.JSON(), nullable=False),
        sa.Column("flags", sa.JSON(), nullable=False),
        sa.Column("retry_count", sa.Integer(), nullable=False),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("task_id", sa.String(length=64), nullable=True),
        sa.Column("queue_backend", sa.String(length=16), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["applicant_id"],
            ["applicants.id"],
        ),
        sa.ForeignKeyConstraint(
            ["owner_user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("applications", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_applications_applicant_id"), ["applicant_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_applications_assigned_to"), ["assigned_to"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_applications_device_id"), ["device_id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_applications_owner_user_id"), ["owner_user_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_applications_state"), ["state"], unique=False)

    op.create_table(
        "application_events",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("application_id", sa.String(length=20), nullable=False),
        sa.Column("from_state", sa.String(length=32), nullable=True),
        sa.Column("to_state", sa.String(length=32), nullable=False),
        sa.Column("actor", sa.String(length=64), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["application_id"],
            ["applications.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("application_events", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_application_events_application_id"), ["application_id"], unique=False
        )

    op.create_table(
        "bureau_reports",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("application_id", sa.String(length=20), nullable=False),
        sa.Column("provider", sa.String(length=24), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["application_id"],
            ["applications.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("bureau_reports", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_bureau_reports_application_id"), ["application_id"], unique=False
        )

    op.create_table(
        "cashflow_features",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("application_id", sa.String(length=20), nullable=False),
        sa.Column("features", sa.JSON(), nullable=False),
        sa.Column("monthly", sa.JSON(), nullable=False),
        sa.Column("categories", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["application_id"],
            ["applications.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("cashflow_features", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_cashflow_features_application_id"), ["application_id"], unique=False
        )

    op.create_table(
        "consents",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("application_id", sa.String(length=20), nullable=False),
        sa.Column("type", sa.String(length=32), nullable=False),
        sa.Column("scope", sa.JSON(), nullable=False),
        sa.Column("text_version", sa.String(length=16), nullable=False),
        sa.Column("granted_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["application_id"],
            ["applications.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("consents", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_consents_application_id"), ["application_id"], unique=False
        )

    op.create_table(
        "decisions",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("application_id", sa.String(length=20), nullable=False),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("outcome", sa.String(length=32), nullable=False),
        sa.Column("conditional", sa.Boolean(), nullable=False),
        sa.Column("pd", sa.Float(), nullable=True),
        sa.Column("score_points", sa.Float(), nullable=True),
        sa.Column("risk_band", sa.String(length=4), nullable=True),
        sa.Column("reason_codes", sa.JSON(), nullable=False),
        sa.Column("rule_set_version", sa.String(length=32), nullable=False),
        sa.Column("model_version", sa.String(length=64), nullable=False),
        sa.Column("feature_snapshot", sa.JSON(), nullable=False),
        sa.Column("feature_hash", sa.String(length=64), nullable=False),
        sa.Column("rule_results", sa.JSON(), nullable=False),
        sa.Column("limits", sa.JSON(), nullable=False),
        sa.Column("pricing", sa.JSON(), nullable=False),
        sa.Column("counterfactuals", sa.JSON(), nullable=False),
        sa.Column("explanation", sa.JSON(), nullable=False),
        sa.Column("challenger", sa.JSON(), nullable=False),
        sa.Column("narratives", sa.JSON(), nullable=False),
        sa.Column("latency_ms", sa.Float(), nullable=False),
        sa.Column("decided_by", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["application_id"],
            ["applications.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("decisions", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_decisions_application_id"), ["application_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_decisions_feature_hash"), ["feature_hash"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_decisions_outcome"), ["outcome"], unique=False)

    op.create_table(
        "documents",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("application_id", sa.String(length=20), nullable=False),
        sa.Column("code", sa.String(length=32), nullable=False),
        sa.Column("filename", sa.String(length=255), nullable=False),
        sa.Column("stored_path", sa.Text(), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("mime", sa.String(length=64), nullable=False),
        sa.Column("size", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("text_source", sa.String(length=16), nullable=True),
        sa.Column("fraud_score", sa.Float(), nullable=False),
        sa.Column("fraud_signals", sa.JSON(), nullable=False),
        sa.Column("uploaded_by", sa.String(length=64), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["application_id"],
            ["applications.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("documents", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_documents_application_id"), ["application_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_documents_sha256"), ["sha256"], unique=False)

    op.create_table(
        "loan_performance",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("application_id", sa.String(length=20), nullable=False),
        sa.Column("month", sa.Integer(), nullable=False),
        sa.Column("dpd", sa.Integer(), nullable=False),
        sa.Column("balance", sa.Float(), nullable=False),
        sa.Column("salary_credited", sa.Boolean(), nullable=False),
        sa.Column("new_bureau_delinquency", sa.Boolean(), nullable=False),
        sa.Column("utilisation", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(
            ["application_id"],
            ["applications.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("loan_performance", schema=None) as batch_op:
        batch_op.create_index("ix_perf_app_month", ["application_id", "month"], unique=False)

    op.create_table(
        "objections",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("application_id", sa.String(length=20), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("due_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("resolved_by", sa.String(length=64), nullable=True),
        sa.Column("resolution", sa.Text(), nullable=True),
        sa.Column("letter", sa.Text(), nullable=True),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["application_id"],
            ["applications.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("objections", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_objections_application_id"), ["application_id"], unique=False
        )

    op.create_table(
        "reviews",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("application_id", sa.String(length=20), nullable=False),
        sa.Column("maker", sa.String(length=64), nullable=False),
        sa.Column("maker_role", sa.String(length=32), nullable=False),
        sa.Column("action", sa.String(length=16), nullable=False),
        sa.Column("amount", sa.Float(), nullable=True),
        sa.Column("term_months", sa.Integer(), nullable=True),
        sa.Column("annual_rate", sa.Float(), nullable=True),
        sa.Column("justification", sa.Text(), nullable=False),
        sa.Column("is_override", sa.Boolean(), nullable=False),
        sa.Column("required_role", sa.String(length=32), nullable=False),
        sa.Column("four_eyes", sa.Boolean(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("checker", sa.String(length=64), nullable=True),
        sa.Column("checker_note", sa.Text(), nullable=True),
        sa.Column("decided_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["application_id"],
            ["applications.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("reviews", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_reviews_application_id"), ["application_id"], unique=False
        )

    op.create_table(
        "extracted_fields",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("document_id", sa.String(length=32), nullable=False),
        sa.Column("application_id", sa.String(length=20), nullable=False),
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("value", sa.Text(), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("page", sa.Integer(), nullable=True),
        sa.Column("bbox", sa.JSON(), nullable=True),
        sa.Column("source", sa.String(length=16), nullable=False),
        sa.Column("corrected_by", sa.String(length=64), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["application_id"],
            ["applications.id"],
        ),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["documents.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("extracted_fields", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_extracted_fields_application_id"), ["application_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_extracted_fields_document_id"), ["document_id"], unique=False
        )

    op.create_table(
        "offers",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("application_id", sa.String(length=20), nullable=False),
        sa.Column("decision_id", sa.String(length=32), nullable=True),
        sa.Column("amount", sa.Float(), nullable=False),
        sa.Column("term_months", sa.Integer(), nullable=False),
        sa.Column("annual_rate", sa.Float(), nullable=False),
        sa.Column("instalment", sa.Float(), nullable=False),
        sa.Column("apr", sa.Float(), nullable=False),
        sa.Column("total_payment", sa.Float(), nullable=False),
        sa.Column("fees", sa.Float(), nullable=False),
        sa.Column("details", sa.JSON(), nullable=False),
        sa.Column("valid_until", sa.DateTime(timezone=True), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("accepted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["application_id"],
            ["applications.id"],
        ),
        sa.ForeignKeyConstraint(
            ["decision_id"],
            ["decisions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("offers", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_offers_application_id"), ["application_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("offers", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_offers_application_id"))

    op.drop_table("offers")
    with op.batch_alter_table("extracted_fields", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_extracted_fields_document_id"))
        batch_op.drop_index(batch_op.f("ix_extracted_fields_application_id"))

    op.drop_table("extracted_fields")
    with op.batch_alter_table("reviews", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_reviews_application_id"))

    op.drop_table("reviews")
    with op.batch_alter_table("objections", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_objections_application_id"))

    op.drop_table("objections")
    with op.batch_alter_table("loan_performance", schema=None) as batch_op:
        batch_op.drop_index("ix_perf_app_month")

    op.drop_table("loan_performance")
    with op.batch_alter_table("documents", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_documents_sha256"))
        batch_op.drop_index(batch_op.f("ix_documents_application_id"))

    op.drop_table("documents")
    with op.batch_alter_table("decisions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_decisions_outcome"))
        batch_op.drop_index(batch_op.f("ix_decisions_feature_hash"))
        batch_op.drop_index(batch_op.f("ix_decisions_application_id"))

    op.drop_table("decisions")
    with op.batch_alter_table("consents", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_consents_application_id"))

    op.drop_table("consents")
    with op.batch_alter_table("cashflow_features", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_cashflow_features_application_id"))

    op.drop_table("cashflow_features")
    with op.batch_alter_table("bureau_reports", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_bureau_reports_application_id"))

    op.drop_table("bureau_reports")
    with op.batch_alter_table("application_events", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_application_events_application_id"))

    op.drop_table("application_events")
    with op.batch_alter_table("applications", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_applications_state"))
        batch_op.drop_index(batch_op.f("ix_applications_owner_user_id"))
        batch_op.drop_index(batch_op.f("ix_applications_device_id"))
        batch_op.drop_index(batch_op.f("ix_applications_assigned_to"))
        batch_op.drop_index(batch_op.f("ix_applications_applicant_id"))

    op.drop_table("applications")
    with op.batch_alter_table("applicants", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_applicants_tckn_bidx"))
        batch_op.drop_index(batch_op.f("ix_applicants_phone_bidx"))
        batch_op.drop_index(batch_op.f("ix_applicants_owner_user_id"))
        batch_op.drop_index(batch_op.f("ix_applicants_iban_bidx"))
        batch_op.drop_index(batch_op.f("ix_applicants_address_bidx"))

    op.drop_table("applicants")
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_users_username"))
        batch_op.drop_index(batch_op.f("ix_users_role"))

    op.drop_table("users")
    op.drop_table("rule_sets")
    with op.batch_alter_table("outbox", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_outbox_status"))
        batch_op.drop_index(batch_op.f("ix_outbox_event"))
        batch_op.drop_index(batch_op.f("ix_outbox_aggregate_id"))

    op.drop_table("outbox")
    op.drop_table("models")
    with op.batch_alter_table("llm_calls", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_llm_calls_application_id"))

    op.drop_table("llm_calls")
    with op.batch_alter_table("audit_log", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_audit_log_entity_id"))
        batch_op.drop_index(batch_op.f("ix_audit_log_action"))

    op.drop_table("audit_log")
    # ### end Alembic commands ###
