"""Offline fairness report for the champion PD model.

Writes ``artifacts/models/fairness.json`` and ``docs/FAIRNESS_REPORT.md``:
selection rates, adverse impact ratio (AIR) and equalised-odds gaps per
protected attribute on the time-based test set, plus the less-discriminatory
alternative trade-off table.

Usage: python scripts/fairness_report.py [--rows 50000]
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from app.core.rules import load_policy_file  # noqa: E402
from app.decisioning.features import MODEL_FEATURES  # noqa: E402
from app.decisioning.models import get_models  # noqa: E402
from app.decisioning.training import SEED, generate_dataset  # noqa: E402
from app.governance.fairness import fairness_report, less_discriminatory_alternatives  # noqa: E402

LABELS = {"gender": "Cinsiyet", "age_band": "Yaş bandı", "province": "İl"}


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--rows", type=int, default=50_000)
    args = parser.parse_args()
    df = generate_dataset(args.rows, SEED)
    test = df[df.application_month > 20].reset_index(drop=True)
    scores = get_models().pd_model.predict_batch(test[list(MODEL_FEATURES)])
    cutoff = load_policy_file().decision.auto_approve_max_pd
    report = fairness_report(test, scores, cutoff)
    report["alternatives"] = less_discriminatory_alternatives(df, list(MODEL_FEATURES), "gender")
    report["test_rows"] = len(test)
    out = ROOT / "artifacts" / "models" / "fairness.json"
    out.write_text(json.dumps(report, ensure_ascii=False, indent=1), encoding="utf-8")

    lines = [
        "# Fairness Report — pd_lgbm_v1",
        "",
        "Generated by `scripts/fairness_report.py` on the time-based test set (application months 21–24) of the seeded "
        f"synthetic population ({len(test):,} applications). Protected / proxy attributes are **not** model inputs; they "
        "are used only for monitoring. Approval = calibrated PD ≤ automatic-approval cut-off "
        f"({cutoff:.0%}).",
        "",
        f"Overall approval rate: **{report['overall_approval_rate']:.1%}**",
        "",
        "## Adverse impact ratio (four-fifths rule)",
        "",
        "| Attribute | Group | Selection rate | AIR |",
        "|---|---|---|---|",
    ]
    for attr, stats in report["attributes"].items():
        for group, rate in stats["selection_rate"].items():
            lines.append(f"| {LABELS[attr]} | {group} | {rate:.1%} | {stats['air'][group]:.2f} |")
    lines += [
        "",
        "| Attribute | Min AIR | Passes 0.8 | Equalised-odds difference |",
        "|---|---|---|---|",
    ]
    for attr, stats in report["attributes"].items():
        lines.append(
            f"| {LABELS[attr]} | {stats['min_air']:.2f} | {'yes' if stats['passes_four_fifths'] else '**no**'} | {stats['equalized_odds_difference']:.3f} |"
        )
    lines += [
        "",
        "## Less discriminatory alternative search (gender)",
        "",
        "| Model | AUC | Approval rate | Min AIR |",
        "|---|---|---|---|",
    ]
    for row in report["alternatives"]:
        lines.append(
            f"| {row['model']} | {row['auc']:.3f} | {row['approval_rate']:.1%} | {row['min_air']:.2f} |"
        )
    lines += [
        "",
        "## Interpretation",
        "",
        "- AIR values below 0.8 raise an alert in `/api/v1/governance/fairness` and on the management dashboard.",
        "- Disparities in the synthetic data stem from the income gap and regional income differences built into the "
        "generator (proxies act through income, not through the protected attribute itself).",
        "- The constrained alternatives quantify how much predictive power (AUC) would be traded for parity; the "
        "model risk committee decides whether a less discriminatory alternative should replace the champion.",
        "- Live monitoring recomputes AIR on real decisions using attributes captured with explicit consent.",
    ]
    (ROOT / "docs" / "FAIRNESS_REPORT.md").write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(
        json.dumps({a: s["min_air"] for a, s in report["attributes"].items()}, ensure_ascii=False)
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
