"""Offline fairness report for the champion PD model.

Writes ``artifacts/models/fairness.json`` and ``docs/FAIRNESS_REPORT.md``:
selection rates, adverse impact ratio (AIR) and equalised-odds gaps per
protected attribute on the time-based test set, plus the less-discriminatory
alternative trade-off table.

Usage: python scripts/fairness_report.py [--rows 100000]
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from app.core.rules import load_policy_file  # noqa: E402
from app.decisioning.features import MODEL_FEATURES  # noqa: E402
from app.decisioning.models import get_models  # noqa: E402
from app.decisioning.training import SEED, generate_dataset  # noqa: E402
from app.governance.fairness import fairness_report, less_discriminatory_alternatives  # noqa: E402

LABELS = {"gender": "Cinsiyet", "age_band": "Yaş bandı", "province": "İl"}


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--rows", type=int, default=100_000)
    args = parser.parse_args()
    df = generate_dataset(args.rows, SEED)
    test = df[df.application_month > 20].reset_index(drop=True)
    scores = get_models().pd_model.predict_batch(test[list(MODEL_FEATURES)])
    cutoff = load_policy_file().decision.auto_approve_max_pd
    report = fairness_report(test, scores, cutoff)
    worst = min(report["attributes"], key=lambda a: report["attributes"][a]["min_air"])
    report["lda_attribute"] = worst
    report["alternatives"] = less_discriminatory_alternatives(
        df, list(MODEL_FEATURES), worst, approval_rate=report["overall_approval_rate"]
    )
    report["test_rows"] = len(test)
    out = ROOT / "artifacts" / "models" / "fairness.json"
    out.write_text(json.dumps(report, ensure_ascii=False, indent=1), encoding="utf-8")

    lines = [
        "# Fairness Report — pd_lgbm_v2 (synthetic population)",
        "",
        "**Real-data fairness is in [`VALIDATION_REPORT.md`](VALIDATION_REPORT.md)** (UCI Taiwan and German Credit, "
        "real SEX / AGE / EDUCATION / MARRIAGE attributes, all models at the same approval rate). This page covers the "
        "synthetic Turkish population only.",
        "",
        "In v1 the protected attributes were generated independently of default, so AIR was good *by construction*. "
        "The generator now builds realistic proxy correlations — tenure grows with age (employment months ≤ working "
        "life since 18), metropolitan provinces earn more, and a gender pay gap — so the numbers below show how "
        "proxies move AIR even though the attributes are never model inputs.",
        "",
        "Generated by `scripts/fairness_report.py` on the time-based test set (application months 21–24) of the seeded "
        f"synthetic population ({len(test):,} applications). Approval = calibrated PD ≤ automatic-approval cut-off "
        f"({cutoff:.0%}).",
        "",
        f"Overall approval rate: **{report['overall_approval_rate']:.1%}**",
        "",
        "## Adverse impact ratio (four-fifths rule)",
        "",
        "| Attribute | Group | Selection rate | AIR |",
        "|---|---|---|---|",
    ]
    for attr, stats in report["attributes"].items():
        for group, rate in stats["selection_rate"].items():
            lines.append(f"| {LABELS[attr]} | {group} | {rate:.1%} | {stats['air'][group]:.2f} |")
    lines += [
        "",
        "| Attribute | Min AIR | Passes 0.8 | Equalised-odds difference |",
        "|---|---|---|---|",
    ]
    for attr, stats in report["attributes"].items():
        lines.append(
            f"| {LABELS[attr]} | {stats['min_air']:.2f} | {'yes' if stats['passes_four_fifths'] else '**no**'} | {stats['equalized_odds_difference']:.3f} |"
        )
    lines += [
        "",
        f"## Less discriminatory alternative search ({LABELS[worst]}, every row at the same approval rate)",
        "",
        "| Model | AUC | Approval rate | Bad rate of approved | Min AIR | TPR gap |",
        "|---|---|---|---|---|---|",
    ]
    for row in report["alternatives"]:
        lines.append(
            f"| {row['model']} | {row['auc']:.3f} | {row['approval_rate']:.1%} | {row['bad_rate_approved']:.1%} "
            f"| {row['min_air']:.2f} | {row['tpr_gap']:.3f} |"
        )
    lines += ["", "## Real-data results (lane A, same approval rate for every model)", ""]
    from app.validation.evidence import available_sets, load_metrics

    lines += [
        "Tied PDs at the cut-off are approved in a seeded random order; the range is the minimum AIR over the "
        "tie-break seeds. An attribute with only one group above the minimum group size is not testable (n/a).",
        "",
        "| Dataset | Champion | Attribute | Min AIR | Range over tie-break seeds | Passes 0.8 | TPR gap |",
        "|---|---|---|---|---|---|---|",
    ]

    def fmt(value: float | None) -> str:
        return "n/a" if value is None else f"{value:.3f}"

    for name in available_sets():
        metrics = load_metrics(name) or {}
        champion = metrics["champion"]["model"]
        for attr, stats in metrics["fairness"]["by_model"][champion].items():
            spread = stats.get("min_air_spread")
            passes = stats["passes_four_fifths"]
            lines.append(
                f"| {name} | {champion} | {attr} | {fmt(stats['min_air'])} | "
                + (f"{spread['min']:.3f}–{spread['max']:.3f}" if spread else "—")
                + f" | {'n/a' if passes is None else 'yes' if passes else '**no**'} | "
                f"{fmt(stats['tpr_gap'])} |"
            )
    lines += [
        "",
        "The synthetic proxies are deliberately mild, so synthetic AIR stays high; the substantive finding is on real "
        "data: on German Credit the champion fails the four-fifths rule for age band. No less discriminatory "
        "alternative stays within the allowed AUC loss on both out-of-fold and hold-out data (the LightGBM family "
        "would raise the age-band AIR to 0.780, still below 0.8, but loses 0.020 AUC out-of-fold), so the finding "
        "is open and goes to the model risk committee (see the LDA tables in `VALIDATION_REPORT.md`).",
        "",
        "## Interpretation",
        "",
        "- AIR values below 0.8 raise an alert in `/api/v1/governance/fairness` and on the management dashboard.",
        "- Disparities in the synthetic data stem from the proxies built into the generator (tenure ↔ age, income ↔ "
        "province and gender); the protected attributes themselves are never model inputs.",
        "- All alternatives are compared at the same approval rate, so an AIR change is a fairness change and not a "
        "volume change. Group-specific thresholds use the protected attribute at decision time and are shown only to "
        "size the trade-off (legally problematic).",
        "- The model risk committee decides whether a less discriminatory alternative should replace the champion.",
        "- Live monitoring recomputes AIR on real decisions using attributes captured with explicit consent.",
    ]
    (ROOT / "docs" / "FAIRNESS_REPORT.md").write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(
        json.dumps({a: s["min_air"] for a, s in report["attributes"].items()}, ensure_ascii=False)
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
